### ISSUE TITLE
TODO: List and prioritization

### ISSUE THREAD

**Issue by mvivopas** [mvivopas/RSNA-2023#10]
# SSH @FrancescVP 

- [ ] Give @mvivopas ssh permissions to access @FrancescVP computer ([tutorial](https://calmcode.io/ssh/introduction.html))

# Base model: @mvivopas 

- [ ] train a model on the whole image (rather than cropped one) -> add a `crop_organ: bool` parameter
- [ ] image normalization (`NormalizeIntensity` from Monai library)
- [ ] skip incomplete organs' images
- [ ] reduce classification task from `injury_low`, `injury_high`, `healthy` to `injury`, `healthy`
- [ ] add a base subsampling strategy

# Simplify and analize @FrancescVP 

- [ ] Save images in numpy format instead of `nii.gz`
- [ ] Extract information from the images volumes to analyze from where the injury-healthy clues could come from
